---
title: "PrevendoEvasao"
author: "Arthur Sena"
date: "06/13/2015"
output: html_document
---

```{r}
library(ggplot2, quietly = T, warn.conflicts = F)
  library(dplyr, quietly = T, warn.conflicts = F)
library("C50")
library("gmodels")
```

```{r}

treino<- read.csv("training_without_accents.txt")
teste <- read.csv("test_without_accents.csv")

 evadiu <- filter(treino, COD_EVASAO == 1, PERIODO_RELATIVO  == 1)
 nao_evadiu <- filter(treino, COD_EVASAO == 0, PERIODO_RELATIVO  == 1)
 treino2 <- rbind(evadiu[1:1000,],nao_evadiu[1:1200,])

treino2[,"COD_EVASAO"]<- as.factor(treino2$COD_EVASAO)
treino2[,"X"] <- NULL
View(treino2)
evasao_model <- C5.0(treino2[,c(3,7,9,10,11)], treino2$COD_EVASAO, na.omit = T)
treino2[,"MEDIA"] <- as.numeric(treino2$MEDIA)
result <- predict(evasao_model,newdata = treino2)
result
CrossTable(treino2$COD_EVASAO, result, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual', 'predicted'))

summary(result)
temp <- as.data.frame(result)
saida <- cbind(teste$ID,temp)
colnames(saida) <- c("ID","COD_EVASAO")
write.csv(saida, file = "Saida2.csv",row.names=F)
```


```{r}
     

getCourses <- function(treino){
  alunos <- levels(as.factor(treino$MATRICULA))    
  
  new_data <- data.frame()
  
  for (aluno in alunos){
       temp <- filter(treino, aluno == as.character(MATRICULA), na.omit = T)
       media <- sum(as.numeric(levels(temp$MEDIA))[temp$MEDIA],na.rm = T)/nrow(temp)
#        print(nrow(temp))
       print(media)
      cod_evasao <- treino %>% filter( aluno ==  as.character(MATRICULA)) %>% select(COD_EVASAO)
     CURSO <- treino %>% filter( aluno ==  as.character(MATRICULA)) %>% select(CURSO)
     SITUACAO <- treino %>% filter( aluno ==  as.character(MATRICULA)) %>% select(SITUACAO)

       new_data <- rbind(new_data,data.frame(aluno,media,cod_evasao,CURSO) )
#        print(media/nrow(temp))
#        print(aluno)
  }
}
getCourses <- function(teste){
  alunos_Teste <- levels(as.factor(teste$MATRICULA))    
  
  new_data2 <- data.frame()
  
  for (aluno in alunos_Teste){
       temp <- filter(teste, aluno == as.character(MATRICULA), na.omit = T)
       media <- sum(temp$MEDIA,na.rm = T)/nrow(temp)
#        print(nrow(temp))
       print(media)
#       cod_evasao <- teste %>% filter( aluno ==  as.character(MATRICULA)) %>% select(COD_EVASAO)
CURSO <- teste %>% filter( aluno ==  as.character(MATRICULA)) %>% select(CURSO)
ID <- teste %>% filter( aluno ==  as.character(MATRICULA)) %>% select(ID)
     SITUACAO <- teste %>% filter( aluno ==  as.character(MATRICULA)) %>% select(SITUACAO)

       new_data2 <- rbind(new_data2,data.frame(aluno,media,CURSO,ID) )
#        print(media/nrow(temp))
#        print(aluno)
  }

getCourses <- function(treino2){
  alunos_Teste <- levels(as.factor(treino2$MATRICULA))    
  
  new_data2 <- data.frame()
  
  for (aluno in alunos_Teste){
       temp <- filter(treino2, aluno == as.character(MATRICULA), na.omit = T)
       media <- sum(temp$MEDIA,na.rm = T)/nrow(temp)
#        print(nrow(temp))
       print(media)
      COD_EVASAO <- treino2 %>% filter( aluno ==  as.character(MATRICULA)) %>% select(COD_EVASAO)
CURSO <- treino2 %>% filter( aluno ==  as.character(MATRICULA)) %>% select(CURSO)
       new_data2 <- rbind(new_data2,data.frame(aluno,media,CURSO,COD_EVASAO) )
#        print(media/nrow(temp))
#        print(aluno)
  }
}

new_data[,"COD_EVASAO"] <- as.factor(new_data$COD_EVASAO)
new_data[,"aluno"] <- as.integer(new_data$aluno)
new_data2[,"aluno"] <- as.integer(new_data2$aluno)

evasao_model <- C5.0(new_data[,c(1,2,4)], new_data$COD_EVASAO, na.omit = T)

result <- predict(evasao_model,newdata = new_data2)

summary(result)
saida3 <- (cbind(new_data2$ID,as.data.frame(result)))
colnames(saida3) <- c("ID","COD_EVASAO")
write.csv(saida3, file = "Saida4.csv",row.names=F)
CrossTable(new_data2$COD_EVASAO, result, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual', 'predicted'))

  }
  
  temp = data.frame()
  
  dpt_exatas <- c("UNID. ACAD. DE MATEMATICA","FISICA I", "UNID. ACAD. DE ESTATISTICA","UNID. ACAD. DE ENGENHARIA ELETRICA","UNID. ACAD. DE ENGENHARIA CIVIL")
  
  
  temp <- mutate(treino,Exatas = DEPARTAMENTO %in% dpt_exatas)
  temp %>% group_by(MATRICULA, Exatas) %>% summarise(COUNT = n())
  temp[,"X"] <- NULL
  
  x<- temp %>% group_by(MATRICULA, Exatas) %>% summarise(MEDIA=mean(MEDIA))
  
  temp %>% group_by(MATRICULA, MEDIA) %>% summarise(=mean())

  
#   temp <- sapply(alunos, function(aluno){
#     
#     disciplinas_do_aluno <- (filter(treino, MATRICULA == aluno))[,"DISCIPLINA"]
#     disciplinas_exatas <-  filter(disciplinas_do_aluno, DISCIPLINA  %in% dpt_exatas)
#     rbind(temp)
#     })
  
  
  #         for (aluno  %in% alunos){
#             disciplinas_do_aluno <- filter(treino, MATRICULA == aluno)
#             cont = 0
#             for (disciplinas %in% disciplinas_do_aluno[,"DISCIPLINA"]){
#               if (disciplinas %in% c("UNID. ACAD. DE MATEMATICA","FISICA I", "UNID. ACAD. DE ESTATISTICA","UNID. ACAD. DE ENGENHARIA ELETRICA")){
#                                         cont = cont + 1
#                 
#               }
#             }
#             temp = rbind(aluno,c(cont))
#         }
        
        
      }
  

```

